/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.process": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.process": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "current-user.destroy": [],
    "sanctum.csrf-cookie": [],
    "api.sync-cart": [],
    "api.provinces": [],
    "api.cities": [],
    "api.destinations": [],
    "api.shipping-cost": [],
    "api.checkout-guest": [],
    "api.check-payment-guest": [],
    "api.vouchers": [],
    "api.check-voucher": [],
    "api.checkout": [],
    "api.cancel-order": [],
    "api.check-payment": [],
    "api.change-payment-type": [],
    "api.confirm-payment": [],
    "api.admin.product-image.index": [],
    "api.admin.product-image.store": [],
    "api.admin.product-image.show": [
        {
            "name": "product_image",
            "required": true
        }
    ],
    "api.admin.product-image.update": [
        {
            "name": "product_image",
            "required": true
        }
    ],
    "api.admin.product-image.destroy": [
        {
            "name": "product_image",
            "required": true
        }
    ],
    "api.my-storebrand.index": [],
    "api.my-storebrand.store": [],
    "api.my-storebrand.show": [
        {
            "name": "brand",
            "required": true
        }
    ],
    "api.my-storebrand.update": [
        {
            "name": "brand",
            "required": true
        }
    ],
    "api.my-storebrand.destroy": [
        {
            "name": "brand",
            "required": true
        }
    ],
    "api.my-storebrand.dropdown": [],
    "api.my-storecustomer.index": [],
    "api.my-storecustomer.store": [],
    "api.my-storecustomer.show": [
        {
            "name": "customer",
            "required": true
        }
    ],
    "api.my-storecustomer.update": [
        {
            "name": "customer",
            "required": true
        }
    ],
    "api.my-storecustomer.destroy": [
        {
            "name": "customer",
            "required": true
        }
    ],
    "api.my-storeproduct.index": [],
    "api.my-storeproduct.store": [],
    "api.my-storeproduct.show": [
        {
            "name": "product",
            "required": true
        }
    ],
    "api.my-storeproduct.update": [
        {
            "name": "product",
            "required": true
        }
    ],
    "api.my-storeproduct.destroy": [
        {
            "name": "product",
            "required": true
        }
    ],
    "api.my-storeproduct-image.index": [],
    "api.my-storeproduct-image.store": [],
    "api.my-storeproduct-image.show": [
        {
            "name": "product_image",
            "required": true
        }
    ],
    "api.my-storeproduct-image.update": [
        {
            "name": "product_image",
            "required": true
        }
    ],
    "api.my-storeproduct-image.destroy": [
        {
            "name": "product_image",
            "required": true
        }
    ],
    "api.my-storeproduct-variant.index": [],
    "api.my-storeproduct-variant.store": [],
    "api.my-storeproduct-variant.show": [
        {
            "name": "product_variant",
            "required": true
        }
    ],
    "api.my-storeproduct-variant.update": [
        {
            "name": "product_variant",
            "required": true
        }
    ],
    "api.my-storeproduct-variant.destroy": [
        {
            "name": "product_variant",
            "required": true
        }
    ],
    "api.my-storeproduct-variant-image.index": [],
    "api.my-storeproduct-variant-image.store": [],
    "api.my-storeproduct-variant-image.show": [
        {
            "name": "product_variant_image",
            "required": true
        }
    ],
    "api.my-storeproduct-variant-image.update": [
        {
            "name": "product_variant_image",
            "required": true
        }
    ],
    "api.my-storeproduct-variant-image.destroy": [
        {
            "name": "product_variant_image",
            "required": true
        }
    ],
    "api.my-storecheckout": [],
    "api.my-storepayment-method.dropdown": [],
    "api.my-storeshipping-method.dropdown": [],
    "api.my-storemidtrans.payment-methods": [],
    "api.my-storeorder.change-status": [],
    "api.my-storereport.generate": [],
    "home": [],
    "catalog": [],
    "product.show": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "my-cart": [],
    "profile": [],
    "profile.update": [],
    "checkout.guest": [],
    "order.success.guest": [],
    "my-order.detail.guest": [
        {
            "name": "invoice_code",
            "required": true
        }
    ],
    "checkout": [],
    "order.success": [],
    "my-order": [],
    "my-order.detail": [
        {
            "name": "invoice_code",
            "required": true
        }
    ],
    "store.create": [],
    "store.store": [],
    "admin.login": [],
    "admin.": [],
    "admin.logout": [],
    "admin.dashboard": [],
    "admin.store.edit": [],
    "admin.store.update": [],
    "admin.certificate": [],
    "admin.certificate.create": [],
    "admin.certificate.store": [],
    "admin.certificate.edit": [
        {
            "name": "storeCertificate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.certificate.update": [
        {
            "name": "storeCertificate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.certificate.destroy": [
        {
            "name": "storeCertificate",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.product": [],
    "admin.product.create": [],
    "admin.product.store": [],
    "admin.product.edit": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.product.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.product.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.index": [],
    "my-store.select-store": [
        {
            "name": "storeId",
            "required": true
        }
    ],
    "my-store.dashboard": [],
    "my-store.store.edit": [],
    "my-store.store.update": [],
    "my-store.certificate": [],
    "my-store.certificate.create": [],
    "my-store.certificate.store": [],
    "my-store.certificate.edit": [
        {
            "name": "storeCertificate",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.certificate.update": [
        {
            "name": "storeCertificate",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.certificate.destroy": [
        {
            "name": "storeCertificate",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.category": [],
    "my-store.category.create": [],
    "my-store.category.store": [],
    "my-store.category.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.category.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.category.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.color": [],
    "my-store.color.create": [],
    "my-store.color.store": [],
    "my-store.color.edit": [
        {
            "name": "color",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.color.update": [
        {
            "name": "color",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.color.destroy": [
        {
            "name": "color",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.size": [],
    "my-store.size.create": [],
    "my-store.size.store": [],
    "my-store.size.edit": [
        {
            "name": "size",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.size.update": [
        {
            "name": "size",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.size.destroy": [
        {
            "name": "size",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.brand": [],
    "my-store.brand.create": [],
    "my-store.brand.store": [],
    "my-store.brand.edit": [
        {
            "name": "brand",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.brand.update": [
        {
            "name": "brand",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.brand.destroy": [
        {
            "name": "brand",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.product": [],
    "my-store.product.create": [],
    "my-store.product.store": [],
    "my-store.product.edit": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.product.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.product.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.transaction": [],
    "my-store.transaction.edit": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.order": [],
    "my-store.order.create": [],
    "my-store.order.edit": [
        {
            "name": "invoice",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.voucher": [],
    "my-store.voucher.create": [],
    "my-store.voucher.store": [],
    "my-store.voucher.edit": [
        {
            "name": "voucher",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.voucher.update": [
        {
            "name": "voucher",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.voucher.destroy": [
        {
            "name": "voucher",
            "required": true,
            "binding": "id"
        }
    ],
    "my-store.customer": [],
    "my-store.report": [],
    "my-store.report.preview": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
